feat: ensemble scoring
numaproj/numalogic-prometheus pull request #92
Opened 2023-03-06 23:26 UTC by ab93

- Enable ensemble scoring
- Add static_threshold_wt field in config

2023-03-07 00:40 UTC, s0nicboOm reviewed
LGTM!

2023-03-07 18:13 UTC, nkoppisetty requested changes

2023-03-07 18:13 UTC, nkoppisetty commented on numaprom/udf/postprocess.py
> +    ensemble_score = (static_wt * norm_static_score) + (model_wt * norm_model_score)
Also, if you are setting default static weight to 0, we would not need separate methods to calculate scores right?

2023-03-07 18:13 UTC, nkoppisetty commented on numaprom/udf/postprocess.py
> +    elif metric_config.static_threshold_wt:
you can just call _calculate_ensemble_score method in else

2023-03-07 18:13 UTC, nkoppisetty commented on numaprom/udf/postprocess.py
> +def _calculate_score(payload: StreamPayload) -> float:
remove this

2023-03-08 01:17 UTC, nkoppisetty approved these changes

2023-03-08 01:18 UTC, merged